general:
  allow-bStats: true
  disable-safe-warning-message: false
  mirai-working-dir: default
bot:
  disable-network-logs: false
  disable-bot-logs: false
  use-bukkit-logger:
    bot-logs: true
    network-logs: true
  log-events: true
  contact-cache:
    enable-friend-list-cache: false
    enable-group-member-list-cache: false
    save-interval-millis: 60000
