name: 问题报告
description: "如果你想反馈 Bug，请使用此模板。"
labels: ["漏洞"]
body:
  - type: markdown
    attributes:
      value: |
        发 issue 前请先看看 [issue 列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)里有没有你的问题，包括已关闭的问题。如有，请关注相关 issue 而不是重复发问。
        如果你不确定你遇到的问题是 MiraiMC 的漏洞还是你自己操作的失误，请先在[讨论·Discussions](https://github.com/DreamVoid/MiraiMC/discussions) 提出。
        请在标题栏中用最简练的语言清晰的描述你遇到的问题，勿增加如“帮帮我”、“急急急”、“大神”之类的无意义词汇。
        滥用 issue 功能将会导致**你被加入黑名单**。
  - type: textarea
    id: description
    attributes: 
      label: 问题描述
      description: 在下方的编辑框描述你的问题
      placeholder: |
        请尽可能说明你遇到的问题，包括你是如何使用插件的，配置文件有没有调过等等。
        请**不要**在这里粘贴日志或配置文件。
    validations:
      required: true
  - type: textarea
    id: recurrent
    attributes: 
      label: 复现方法
      description: 在下方的编辑框描述如何触发这个漏洞（分步需换行请直接回车，会为你添加标号）
      placeholder: 能看到这个？说明你没有看描述，请自己加上“1. ”进行分步描述步骤。
      value: "1. "
    validations:
      required: true
  - type: dropdown
    id: servertype
    attributes: 
      label: 服务端类型
      description: 选择你正在使用的服务端类型
      options: 
        - Bukkit
        - BungeeCord
        - Sponge
        - Velocity
        - Nukkit
    validations:
      required: true
  - type: input
    id: serverversion
    attributes:
      label: 服务端版本
      description: 填写你正在使用的服务端版本，例如 Paper-1.12.2
      placeholder: 在服务端输入 /ver 查看版本
    validations:
      required: true
  - type: input
    id: pluginversion
    attributes:
      label: MiraiMC 插件版本
      description: 填写你正在使用的 MiraiMC 版本，例如 1.7-pre2 或 dev-200
      placeholder: 在服务端输入 /miraimc 查看版本
    validations:
      required: true
  - type: textarea
    id: serverlog
    attributes: 
      label: 服务端日志
      description: |
        在下方复制你的服务端日志
        如果日志超出字数限制，请在 https://mclo.gs/ 上传日志文件，在下方填写链接。
      placeholder: |
        请提供 latest.log 文件的所有内容，自以为知道问题所在而提供不完整的日志将被直接关闭。
        如果日志超出字数限制，请在 https://mclo.gs/ 上传日志文件，在这里填写链接。
        除了日志内容或链接，在这里填写任何无关文字将会导致 issue 被直接关闭，并会视为滥用 issue。
      render: text
    validations:
      required: true
  - type: textarea
    id: extra
    attributes: 
      label: 额外说明
      description: 还有什么要补充的吗？
      placeholder: |
        提示：
        你可以提供系统环境、Java版本、你使用了什么依赖MiraiMC的插件、重置插件配置后问题是否仍然存在、你使用的插件列表
        你还可以提供截图和文件（直接拖动文件到编辑框）
  - type: checkboxes
    id: agreement
    attributes:
      label: 协议
      description: 请同意下列条款
      options:
        - label: 我已查阅[常见问题疑难解答](https://docs.miraimc.dreamvoid.me/troubleshoot/faq)和 [issue 列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
          required: true
        - label: 我确认我已认真阅读所有注意事项并认真填写表单。
          required: true
        - label: 我确认我没有看这些选择框就随便勾选了。
          required: false
        - label: 我明白，如果没有正确填写 issue 模板的内容，本 issue 将会直接被关闭并被锁定。
          required: true
        - label: 我明白，如果滥用 issue 功能，我将会被列入黑名单。
          required: true
