name: 开发者问题报告
description: "如果你想反馈基于 MiraiMC 开发时出现的问题，请使用此模板。"
labels: ["开发问题"]
body:
  - type: markdown
    attributes:
      value: |
        发 issue 前请先看看 [issue 列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)里有没有你的问题，包括已关闭的问题。如有，请关注相关 issue 而不是重复发问。
        如果你不确定你遇到的问题是 MiraiMC 的问题还是你自己操作的失误，请先在[讨论·Discussions](https://github.com/DreamVoid/MiraiMC/discussions) 提出。
        请在标题栏中用最简练的语言清晰的描述你遇到的问题，勿增加如“帮帮我”、“急急急”、“大神”之类的无意义词汇。
        滥用 issue 功能将会导致**你被加入黑名单**。
  - type: textarea
    id: description
    attributes: 
      label: 问题描述
      description: 在下方的编辑框描述你的问题
      placeholder: |
        请尽可能说明你遇到的问题，包括你调用了 MiraiMC 的什么代码，MiraiMC 没有按预期工作的表现。
        请**不要**在这里粘贴日志、配置文件或代码。
    validations:
      required: true
  - type: textarea
    id: recurrent
    attributes: 
      label: 复现方法
      description: 在下方的代码编辑框描述如何触发这个问题
      placeholder: 描述如何使用代码触发此问题
      render: java
    validations:
      required: true
  - type: dropdown
    id: servertype
    attributes: 
      label: 服务端类型
      description: 选择你正在开发的插件适用的服务端类型
      options: 
        - Bukkit
        - BungeeCord
        - Sponge
        - Velocity
        - Nukkit
    validations:
      required: true
  - type: input
    id: serverversion
    attributes:
      label: 服务端版本
      description: 填写你正在使用的服务端版本，例如 Paper-1.12.2
      placeholder: 在服务端输入 /ver 查看版本
    validations:
      required: true
  - type: input
    id: pluginversion
    attributes:
      label: MiraiMC 插件版本
      description: 填写你正在使用的 MiraiMC 版本，例如 1.7-pre2 或 dev-200
      placeholder: 在服务端输入 /miraimc 查看版本
    validations:
      required: true
  - type: textarea
    id: serverlog
    attributes: 
      label: 服务端日志
      description: 在下方复制你的服务端日志
      placeholder: |
        请提供出问题时 MiraiMC 的日志输出内容，如果涉及了 mirai，请上传完整服务端日志。
        如果日志超出字数限制，请在 https://mclo.gs/ 上传日志文件，在这里填写链接。
        如果 MiraiMC 没有日志输出，可不填写此段
      render: text
    validations:
      required: false
  - type: textarea
    id: extra
    attributes: 
      label: 额外说明
      description: 还有什么要补充的吗？
      placeholder: |
        提示：
        你可以提供系统环境、Java版本、你的代码仓库链接
        你还可以提供截图和文件（直接拖动文件到编辑框）
  - type: checkboxes
    id: agreement
    attributes:
      label: 协议
      description: 请同意下列条款
      options:
        - label: 我已查阅[常见问题疑难解答](https://docs.miraimc.dreamvoid.me/troubleshoot/faq)和 [issue 列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
          required: true
        - label: 我确认我已认真阅读所有注意事项并认真填写表单。
          required: true
        - label: 我确认我没有看这些选择框就随便勾选了。
          required: false
        - label: 我明白，如果没有正确填写 issue 模板的内容，本 issue 将会直接被关闭并被锁定。
          required: true
        - label: 我明白，如果滥用 issue 功能，我将会被列入黑名单。
          required: true
