# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'zulu'
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Upload a Build Artifact - MiraiMC Bukkit
      uses: actions/upload-artifact@v2.3.1
      with:
        # Artifact name
        name: "MiraiMC Bukkit"
        # A file, directory or wildcard pattern that describes what to upload
        path: MiraiMC-Bukkit/target/MiraiMC-Bukkit.jar
        # The desired behavior if no files are found using the provided path.

    - name: Upload a Build Artifact - MiraiMC Bungee
      uses: actions/upload-artifact@v2.3.1
      with:
        # Artifact name
        name: "MiraiMC Bungee"
        # A file, directory or wildcard pattern that describes what to upload
        path: MiraiMC-Bungee/target/MiraiMC-Bungee.jar
        # The desired behavior if no files are found using the provided path.

    - name: Upload a Build Artifact - MiraiMC Sponge
      uses: actions/upload-artifact@v2.3.1
      with:
        # Artifact name
        name: "MiraiMC Sponge"
        # A file, directory or wildcard pattern that describes what to upload
        path: MiraiMC-Sponge/target/MiraiMC-Sponge.jar
        # The desired behavior if no files are found using the provided path.

    - name: Upload a Build Artifact - MiraiMC Nukkit
      uses: actions/upload-artifact@v2.3.1
      with:
        # Artifact name
        name: "MiraiMC Nukkit"
        # A file, directory or wildcard pattern that describes what to upload
        path: MiraiMC-Nukkit/target/MiraiMC-Nukkit.jar
        # The desired behavior if no files are found using the provided path.
