# This is a basic workflow to help you get started with Actions

name: Gitee Auto Sync

# Controls when the workflow will run
on: 
  push:
  workflow_dispatch:
  release:
    types: # This configuration does not affect the page_build event above
      - created

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Hub Mirror Action.
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/DreamVoid
          dst: gitee/dreamvoid
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          static_list: "MiraiMC"
